name: Checkmarx
    
on:
#   push:
#     branches: ['master']
#   pull_request:
#     branches: ['master']
  workflow_dispatch:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkmarx CxFlow Action
            # You may pin to the exact commit or the version.
            # uses: checkmarx-ts/checkmarx-cxflow-github-action@49d8269b14ca87910ba003d47a31fa0c7a11f2fe
              uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.5
              with:
                    # Provide Checkmarx URL
                    checkmarx_url: https://partners9x.checkmarx.net/
                    # Select a Checkmarx Team (optional)
                    team: /CxServer/servicenow
                    # Provide Checkmarx Username
                    checkmarx_username: servicenow
                    # Provide Checkmarx Password
                    checkmarx_password: Cx12345678! 
                    # Provide Checkmarx Client Secret
                    checkmarx_client_secret: 014DF517-39D1-4453-B7B3-9930C563627C 
                    # Select a Checkmarx Project
                    project: DevOpsSpring
                    # Vulnerability Scanners (sast, sca, cxgo)
                    scanners: sast 
